const DataAcara2 = [
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Halaqoh Tarbiyah",
    masjid2: "Masjid Al-Insan",
    tanggal2: "Senin, 18 September 2023",
    hari: "Senin",
    tanggalShort: "18 Sep",
    tagline:
      "Hadirilah dan temukan inspirasi hidup dalam Halaqoh Tarbiyah kami",
    pukul: "20.00 WIB",
    deskripsi: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit suscipit quo dolor tempora 
      incidunt facilis doloremque consequuntur nostrum odio nam!`,
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Tabligh Akbar",
    masjid2: "Masjid Baiturrahim",
    tanggal2: "Rabu, 20 September 2023",
    hari: "Rabu",
    tanggalShort: "20 Sep",
    tagline: "Mari merapatkan barisan dalam kebersamaan agung!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Kuliah Umum",
    masjid2: "Masjid Al-Hidayah",
    tanggal2: "Juma`at, 22 September 2023",
    hari: "Jum`at",
    tanggalShort: "22 Sep",
    tagline: "Jangan lewatkan kesempatan emas untuk menyaksikan dan belajar...",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
  {
    poster: "/src/assets/ImageAcara/MaulidNabi.png",
    acara2: "Nuzulul Qur`an",
    masjid2: "Masjid An-Nahl",
    tanggal2: "Ahad, 24 September 2023",
    hari: "Ahad",
    tanggalShort: "24 Sep",
    tagline: "Sambutlah malam penuh berkah Nuzulul Quran bersama kami!",
  },
];

export default DataAcara2;
